// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AssessmentCoposeMailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void assessmentCoposeMail() {
    // Test name: AssessmentCoposeMail
    // Step # | name | target | value | comment
    // 1 | open | /manage_account?pspid=159600001&activity=mail-direct&.lang=en-US&.intl=us&src=ym&signin=true&done=https%3A%2F%2Fmail.yahoo.com%2Fd&eid=100 |  | 
    driver.get("https://login.yahoo.com/manage_account?pspid=159600001&activity=mail-direct&.lang=en-US&.intl=us&src=ym&signin=true&done=https%3A%2F%2Fmail.yahoo.com%2Fd&eid=100");
    // 2 | setWindowSize | 629x835 |  | 
    driver.manage().window().setSize(new Dimension(629, 835));
    // 3 | click | name=username |  | 
    driver.findElement(By.name("username")).click();
    // 4 | click | id=login-passwd |  | 
    driver.findElement(By.id("login-passwd")).click();
    // 5 | type | id=login-passwd | Encrypted | 
    driver.findElement(By.id("login-passwd")).sendKeys("Encrypted");
    // 6 | click | id=login-signin |  | 
    driver.findElement(By.id("login-signin")).click();
    // 7 | click | linkText=Compose |  | 
    driver.findElement(By.linkText("Compose")).click();
    // 8 | click | id=to |  | 
    driver.findElement(By.id("to")).click();
    // 9 | type | id=to | olukareh_bukky@yahoo.com | 
    driver.findElement(By.id("to")).sendKeys("olukareh_bukky@yahoo.com");
    // 10 | click | id=subject |  | 
    driver.findElement(By.id("subject")).click();
    // 11 | type | id=subject | hi | 
    driver.findElement(By.id("subject")).sendKeys("hi");
    // 12 | click | id=editorPlainText |  | 
    driver.findElement(By.id("editorPlainText")).click();
    // 13 | type | id=editorPlainText | Automation test | 
    driver.findElement(By.id("editorPlainText")).sendKeys("Automation test");
    // 14 | click | name=action |  | 
    driver.findElement(By.name("action")).click();
    // 15 | click | css=.u_b > .J_x |  | 
    driver.findElement(By.cssSelector(".u_b > .J_x")).click();
    // 16 | click | linkText=me |  | 
    driver.findElement(By.linkText("me")).click();
    // 17 | click | name=jumpTo |  | 
    driver.findElement(By.name("jumpTo")).click();
    // 18 | click | linkText=Sign Out |  | 
    driver.findElement(By.linkText("Sign Out")).click();
  }
}
